spring.application.name=denti_back

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://denti-db.cxaegcc6y0xu.ap-northeast-2.rds.amazonaws.com:3306/denti_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=denti
spring.datasource.password=1q2w3e4r

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=30MB

ai.server.url=http://172.31.37.45:5000

file.upload-dir=/app/uploads/ai

file.community-upload-dir=/app/uploads/community

# ===== 카카오 소셜 로그인 =====
spring.security.oauth2.client.registration.kakao.client-id=0a494325a827d358e9813340e3758e13
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.kakao.scope=profile_nickname
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.client-secret=JjKJaHBw4pA0TMhZGkGVv2uGmws8896m

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

oauth2.success-redirect-url=http://localhost:5173/oauth/callback
